--DROP TABLE IF EXISTS users;
--
--CREATE TABLE users (
--  username INT AUTO_INCREMENT  PRIMARY KEY,
--  password VARCHAR(250) NOT NULL,
--  first_name VARCHAR(250) NOT NULL,
--  last_name VARCHAR(250) NOT NULL
--);
--
--INSERT INTO users (username, password, first_name, last_name) VALUES
--  ('admin', 'admin', 'John', 'Doe'),
--  ('user', 'pass', 'John', 'Doe 2');